version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - chatapp1
      - chatapp2
      - chatapp3
      - chatapp4
    networks: 
      - chatnetwork

  chatapp1:
    image: chatapp
    hostname: 'chatapp1'
    environment:
      - SERVER_NAME=chatAPP-1
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/chat_db
    depends_on: 
      - rds
      - mongo
    networks: 
      - chatnetwork
    

  chatapp2:
    image: chatapp
    hostname: 'chatapp2'
    environment:
      - SERVER_NAME=chatAPP-2
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/chat_db
    depends_on: 
      - rds
      - mongo    
    networks: 
      - chatnetwork

  chatapp3:
    image: chatapp
    hostname: 'chatapp3'
    environment:
      - SERVER_NAME=chatAPP-3
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/chat_db
    depends_on: 
      - rds
      - mongo
    networks: 
      - chatnetwork

  chatapp4:
    image: chatapp
    hostname: 'chatapp4'
    environment:
      - SERVER_NAME=chatAPP-4
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/chat_db
    depends_on: 
      - rds
      - mongo
    networks: 
      - chatnetwork
    
  rds:
    image: redis:3
    ports:
      - "6379:6379"
    networks: 
      - chatnetwork
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks: 
      - chatnetwork

volumes:
  mongo_data:
  
networks:
  chatnetwork: {}